version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_biblioteca
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: biblioteca
    ports:
      - "3306:3306"
    volumes:
      - ./BD/sql_biblioteca.sql:/docker-entrypoint-initdb.d/sql_biblioteca.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_biblioteca
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=biblioteca
    volumes:
      - ./backend:/usr/src/app
    command: npm run start

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_biblioteca
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - backend
